name: CI/CD - Verificação HTML

on:
  pull_request:
    branches: [main]

jobs:
  html-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar htmlhint
        run: npm install -g htmlhint

      - name: Verificar HTML
        run: htmlhint index.html

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        

      - name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: |
            index.html      